In [9]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

- 전처리

In [13]:
pima = pd.read_csv('pima-indians-diabetes.csv', skiprows = 9, header = None)
pima

0    1   2   3    4     5      6   7  8
0     6  148  72  35    0  33.6  0.627  50  1
1     1   85  66  29    0  26.6  0.351  31  0
2     8  183  64   0    0  23.3  0.672  32  1
3     1   89  66  23   94  28.1  0.167  21  0
4     0  137  40  35  168  43.1  2.288  33  1
..   ..  ...  ..  ..  ...   ...    ...  .. ..
763  10  101  76  48  180  32.9  0.171  63  0
764   2  122  70  27    0  36.8  0.340  27  0
765   5  121  72  23  112  26.2  0.245  30  0
766   1  126  60   0    0  30.1  0.349  47  1
767   1   93  70  31    0  30.4  0.315  23  0

[768 rows x 9 columns]

In [14]:
pima[8].value_counts()

0    500
1    268
Name: 8, dtype: int64

In [15]:
pima.data = pima.iloc[:, :8]
pima.target = pima[8]

<ipython-input-15-8322d7b1d0bc>:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  pima.data = pima.iloc[:, :8]
<ipython-input-15-8322d7b1d0bc>:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  pima.target = pima[8]


- Train/Test 분류

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    pima.data, pima.target, stratify = pima[8], random_state = 2021
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((576, 8), (192, 8), (576,), (192,))

In [17]:
pd.Series(y_test).value_counts()

0    125
1     67
Name: 8, dtype: int64

- 모델 생성

In [18]:
dtc = DecisionTreeClassifier(random_state = 2021)
dtc.fit(X_train, y_train)

DecisionTreeClassifier(random_state=2021)

In [10]:
svc = SVC()
svc.fit(X_train, y_train)

SVC()

In [11]:
lr =LogisticRegression()
lr.fit(X_train, y_train)

/Users/eugene/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

- 예측

In [21]:
pred_dtc = dtc.predict(X_test)
pred_svc = svc.predict(X_test)
pred_lr = lr.predict(X_test)

- 평가

In [24]:
score_dtc = accuracy_score(y_test, pred_dtc)
score_svc = accuracy_score(y_test, pred_svc)
score_lr = accuracy_score(y_test, pred_lr)
score_dtc, score_svc, score_lr

(0.7395833333333334, 0.7552083333333334, 0.8125)

In [26]:
dtc.score(X_test, y_test), svc.score(X_test, y_test), lr.score(X_test, y_test)

(0.7395833333333334, 0.7552083333333334, 0.8125)

In [28]:
pred_df = pd.DataFrame({
    'Original' : y_test,
    'Decision Tree' : pred_dtc,
    'SVM' : pred_svc,
    'Logistic Regression' : pred_lr
})
pred_df

Original  Decision Tree  SVM  Logistic Regression
41          0              1    0                    1
149         0              0    0                    0
489         0              0    1                    1
418         0              0    0                    0
217         0              1    0                    0
..        ...            ...  ...                  ...
237         1              1    1                    1
317         1              1    1                    1
486         0              0    1                    0
620         0              0    0                    0
136         0              0    0                    0

[192 rows x 4 columns]

- de 모델생성 à 평가

In [41]:
from sklearn.model_selection import cross_val_score

scores_dtc = cross_val_score(dtc, pima.data, pima.target, cv = 5)
scores_svc = cross_val_score(svc, pima.data, pima.target, cv = 5)
scores_lr = cross_val_score(lr, pima.data, pima.target, cv = 5)

/Users/eugene/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/eugene/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#log

In [43]:
scores_dtc, scores_svc, scores_lr

(array([0.67532468, 0.67532468, 0.7012987 , 0.77777778, 0.73856209]),
 array([0.74675325, 0.73376623, 0.77272727, 0.79084967, 0.75163399]),
 array([0.77272727, 0.74675325, 0.75974026, 0.81699346, 0.75163399]))

In [44]:
np.mean(score_dtc), np.mean(scores_svc), np.mean(scores_lr)

(0.7395833333333334, 0.7591460826754943, 0.7695696460402341)

In [95]:
from sklearn.model_selection import GridSearchCV
params_dtc = {
    'max_depth' : [1, 2, 4, 6, 8],
    'min_samples_split' : [2, 3, 4]
}

grid_dtc = GridSearchCV(dtc, param_grid = params_dtc, cv = 3)
grid_dtc.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(random_state=2021),
             param_grid={'max_depth': [1, 2, 4, 6, 8],
                         'min_samples_split': [2, 3, 4]})

In [93]:
params_svc = {
    'C' : [0.001, 0.01, 0.1, 1, 10]
}

grid_svc = GridSearchCV(svc, param_grid = params_svc, cv = 3)
grid_svc.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=SVC(), param_grid={'C': [0.001, 0.01, 0.1, 1, 10]})

In [107]:
params_lr = {
    'C' : [0.01, 0.1, 1, 10]
}

grid_lr = GridSearchCV(lr, param_grid = params_lr, cv = 3)
grid_lr.fit(X_train, y_train)

/Users/eugene/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/eugene/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#log

GridSearchCV(cv=3, estimator=LogisticRegression(),
             param_grid={'C': [0.01, 0.1, 1, 10]})

In [96]:
grid_dtc.cv_results_

{'mean_fit_time': array([0.00215435, 0.00163198, 0.001695  , 0.0019052 , 0.00185982,
        0.00161449, 0.00189328, 0.00188073, 0.00177487, 0.00214958,
        0.0021557 , 0.00209761, 0.00225846, 0.00223724, 0.00227833]),
 'std_fit_time': array([3.29664362e-04, 4.96349843e-05, 8.25016327e-05, 3.19824698e-05,
        2.41996724e-04, 6.86271037e-05, 2.96739356e-05, 1.55478693e-04,
        3.22246522e-05, 7.99675486e-05, 8.00843555e-05, 4.00377610e-05,
        4.49191121e-05, 5.14897047e-05, 2.22525228e-04]),
 'mean_score_time': array([0.00101105, 0.00143592, 0.00092578, 0.0010728 , 0.00089765,
        0.00087833, 0.00092411, 0.00084734, 0.00087245, 0.00086538,
        0.00104221, 0.00086276, 0.00090655, 0.00091219, 0.00086029]),
 'std_score_time': array([5.66297523e-05, 7.82854326e-04, 6.62652120e-05, 1.20099295e-04,
        8.20049012e-05, 5.08865906e-05, 8.69695291e-05, 6.36754684e-05,
        8.19564420e-05, 1.80110820e-05, 1.43293379e-04, 3.33975178e-06,
        3.43390814e-05, 4.94

In [101]:
grid_dtc.best_score_, grid_dtc.best_params_, grid_dtc.best_estimator_

(0.7256944444444445,
 {'max_depth': 4, 'min_samples_split': 4},
 DecisionTreeClassifier(max_depth=4, min_samples_split=4, random_state=2021))

In [100]:
pred = grid_dtc.best_estimator_.predict(X_test)
accuracy_score(y_test, pred)

0.75

In [102]:
grid_svc.cv_results_

{'mean_fit_time': array([0.00858426, 0.00710766, 0.00696707, 0.00658282, 0.00635831]),
 'std_fit_time': array([1.29909317e-03, 1.29235088e-04, 1.63521082e-05, 1.80321099e-05,
        2.11121353e-04]),
 'mean_score_time': array([0.00657733, 0.00613157, 0.00598296, 0.0054516 , 0.00492032]),
 'std_score_time': array([0.00060536, 0.00011913, 0.00010498, 0.00011545, 0.00015552]),
 'param_C': masked_array(data=[0.001, 0.01, 0.1, 1, 10],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 0.001}, {'C': 0.01}, {'C': 0.1}, {'C': 1}, {'C': 10}],
 'split0_test_score': array([0.65104167, 0.65104167, 0.65625   , 0.734375  , 0.72395833]),
 'split1_test_score': array([0.65104167, 0.65104167, 0.65104167, 0.76041667, 0.765625  ]),
 'split2_test_score': array([0.65104167, 0.65104167, 0.65104167, 0.72916667, 0.72916667]),
 'mean_test_score': array([0.65104167, 0.65104167, 0.65277778, 0.74131944, 0.73958333]),
 'std_test_score': arr

In [103]:
grid_svc.best_score_, grid_svc.best_params_, grid_svc.best_estimator_

(0.7413194444444443, {'C': 1}, SVC(C=1))

In [104]:
pred = grid_dtc.best_estimator_.predict(X_test)
accuracy_score(y_test, pred)

0.75

In [108]:
grid_lr.cv_results_

{'mean_fit_time': array([0.01667627, 0.01193953, 0.012158  , 0.01130891]),
 'std_fit_time': array([0.0035004 , 0.00022374, 0.00066456, 0.00047427]),
 'mean_score_time': array([0.00130471, 0.00092594, 0.00096194, 0.00089097]),
 'std_score_time': array([2.40091600e-04, 2.83235742e-05, 1.34255043e-05, 3.60703489e-05]),
 'param_C': masked_array(data=[0.01, 0.1, 1, 10],
              mask=[False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 0.01}, {'C': 0.1}, {'C': 1}, {'C': 10}],
 'split0_test_score': array([0.75520833, 0.734375  , 0.734375  , 0.73958333]),
 'split1_test_score': array([0.796875  , 0.77083333, 0.8125    , 0.80729167]),
 'split2_test_score': array([0.74479167, 0.734375  , 0.734375  , 0.72395833]),
 'mean_test_score': array([0.765625  , 0.74652778, 0.76041667, 0.75694444]),
 'std_test_score': array([0.02250257, 0.01718662, 0.03682848, 0.03616782]),
 'rank_test_score': array([1, 4, 2, 3], dtype=int32)}

In [111]:
grid_lr.best_score_, grid_lr.best_params_, grid_lr.best_estimator_

(0.765625, {'C': 0.01}, LogisticRegression(C=0.01))

In [110]:
pred = grid_lr.best_estimator_.predict(X_test)
accuracy_score(y_test, pred)

0.8020833333333334