In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

- 전처리

In [4]:
pima = pd.read_csv('pima-indians-diabetes.csv', skiprows = 9, header = None)
pima

0    1   2   3    4     5      6   7  8
0     6  148  72  35    0  33.6  0.627  50  1
1     1   85  66  29    0  26.6  0.351  31  0
2     8  183  64   0    0  23.3  0.672  32  1
3     1   89  66  23   94  28.1  0.167  21  0
4     0  137  40  35  168  43.1  2.288  33  1
..   ..  ...  ..  ..  ...   ...    ...  .. ..
763  10  101  76  48  180  32.9  0.171  63  0
764   2  122  70  27    0  36.8  0.340  27  0
765   5  121  72  23  112  26.2  0.245  30  0
766   1  126  60   0    0  30.1  0.349  47  1
767   1   93  70  31    0  30.4  0.315  23  0

[768 rows x 9 columns]

In [14]:
pima[8].value_counts()

0    500
1    268
Name: 8, dtype: int64

In [5]:
pima.data = pima.iloc[:, :8]
pima.target = pima[8]

<ipython-input-5-8322d7b1d0bc>:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  pima.data = pima.iloc[:, :8]
<ipython-input-5-8322d7b1d0bc>:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  pima.target = pima[8]


- Train/Test 분류

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    pima.data, pima.target, stratify = pima.target, random_state = 2021
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((576, 8), (192, 8), (576,), (192,))

In [9]:
pd.Series(y_test).value_counts()

0    125
1     67
Name: 8, dtype: int64

- 모델 생성

In [10]:
dtc = DecisionTreeClassifier(random_state = 2021)
dtc.fit(X_train, y_train)

DecisionTreeClassifier(random_state=2021)

In [11]:
svc = SVC()
svc.fit(X_train, y_train)

SVC()

In [12]:
lr =LogisticRegression()
lr.fit(X_train, y_train)

/Users/eugene/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

- 예측

In [13]:
pred_dtc = dtc.predict(X_test)
pred_svc = svc.predict(X_test)
pred_lr = lr.predict(X_test)

- 평가

In [14]:
score_dtc = accuracy_score(y_test, pred_dtc)
score_svc = accuracy_score(y_test, pred_svc)
score_lr = accuracy_score(y_test, pred_lr)
score_dtc, score_svc, score_lr

(0.7395833333333334, 0.7552083333333334, 0.8125)

In [15]:
dtc.score(X_test, y_test), svc.score(X_test, y_test), lr.score(X_test, y_test)

(0.7395833333333334, 0.7552083333333334, 0.8125)

In [16]:
pred_df = pd.DataFrame({
    'Original' : y_test,
    'Decision Tree' : pred_dtc,
    'SVM' : pred_svc,
    'Logistic Regression' : pred_lr
})
pred_df

Original  Decision Tree  SVM  Logistic Regression
41          0              1    0                    1
149         0              0    0                    0
489         0              0    1                    1
418         0              0    0                    0
217         0              1    0                    0
..        ...            ...  ...                  ...
237         1              1    1                    1
317         1              1    1                    1
486         0              0    1                    0
620         0              0    0                    0
136         0              0    0                    0

[192 rows x 4 columns]

- de 모델생성 à 평가

In [17]:
from sklearn.model_selection import cross_val_score

scores_dtc = cross_val_score(dtc, pima.data, pima.target, cv = 5)
scores_svc = cross_val_score(svc, pima.data, pima.target, cv = 5)
scores_lr = cross_val_score(lr, pima.data, pima.target, cv = 5)

/Users/eugene/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/eugene/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#log

In [18]:
scores_dtc, scores_svc, scores_lr

(array([0.67532468, 0.67532468, 0.7012987 , 0.77777778, 0.73856209]),
 array([0.74675325, 0.73376623, 0.77272727, 0.79084967, 0.75163399]),
 array([0.77272727, 0.74675325, 0.75974026, 0.81699346, 0.75163399]))

In [19]:
np.mean(score_dtc), np.mean(scores_svc), np.mean(scores_lr)

(0.7395833333333334, 0.7591460826754943, 0.7695696460402341)

In [37]:
from sklearn.model_selection import GridSearchCV
params_dtc = {
    'max_depth' : [1, 2, 4, 6, 8],
    'min_samples_split' : [2, 3, 4]
}

grid_dtc = GridSearchCV(dtc, param_grid = params_dtc, cv = 3)
grid_dtc.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(random_state=2021),
             param_grid={'max_depth': [1, 2, 4, 6, 8],
                         'min_samples_split': [2, 3, 4]})

In [21]:
params_svc = {
    'C' : [0.001, 0.01, 0.1, 1, 10]
}

grid_svc = GridSearchCV(svc, param_grid = params_svc, cv = 3)
grid_svc.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=SVC(), param_grid={'C': [0.001, 0.01, 0.1, 1, 10]})

In [22]:
params_lr = {
    'C' : [0.01, 0.1, 1, 10]
}

grid_lr = GridSearchCV(lr, param_grid = params_lr, cv = 3)
grid_lr.fit(X_train, y_train)

/Users/eugene/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/eugene/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#log

GridSearchCV(cv=3, estimator=LogisticRegression(),
             param_grid={'C': [0.01, 0.1, 1, 10]})

In [38]:
grid_dtc.cv_results_

{'mean_fit_time': array([0.00205135, 0.00142964, 0.00157706, 0.00169969, 0.00159446,
        0.00155735, 0.00194947, 0.00191784, 0.00171447, 0.00188899,
        0.00194391, 0.00189455, 0.00202894, 0.00203554, 0.00198428]),
 'std_fit_time': array([2.09124582e-04, 3.36557943e-05, 8.22398577e-05, 1.18982099e-04,
        9.75768794e-05, 1.21632426e-05, 7.48744006e-05, 6.36477885e-05,
        5.92190669e-05, 9.17834118e-06, 8.97892796e-05, 2.15311324e-06,
        6.08862735e-05, 8.01770483e-06, 4.43724811e-05]),
 'mean_score_time': array([0.0010496 , 0.00082628, 0.00089741, 0.00085322, 0.00083423,
        0.00082469, 0.00091132, 0.00086522, 0.00077415, 0.00081539,
        0.00077796, 0.00077923, 0.0007894 , 0.00081968, 0.00076358]),
 'std_score_time': array([1.49858590e-04, 2.01312770e-05, 3.00653296e-05, 2.01388053e-05,
        5.16398718e-05, 6.24456446e-06, 2.12235690e-05, 1.94988892e-05,
        1.24845767e-05, 8.58573960e-05, 7.76478716e-06, 6.67098801e-06,
        2.22841672e-05, 6.96

In [39]:
grid_dtc.best_score_, grid_dtc.best_params_, grid_dtc.best_estimator_

(0.7256944444444445,
 {'max_depth': 4, 'min_samples_split': 4},
 DecisionTreeClassifier(max_depth=4, min_samples_split=4, random_state=2021))

In [40]:
pred = grid_dtc.best_estimator_.predict(X_test)
accuracy_score(y_test, pred)

0.75

In [26]:
grid_svc.cv_results_

{'mean_fit_time': array([0.00767724, 0.00706275, 0.00698463, 0.00657868, 0.00644302]),
 'std_fit_time': array([5.16568954e-04, 1.96715347e-04, 1.88881425e-05, 8.60584293e-05,
        2.15638325e-04]),
 'mean_score_time': array([0.00634845, 0.00607634, 0.00599305, 0.00552003, 0.00496936]),
 'std_score_time': array([4.04902529e-04, 1.18686164e-04, 8.80506924e-05, 8.35468809e-05,
        1.49552255e-04]),
 'param_C': masked_array(data=[0.001, 0.01, 0.1, 1, 10],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 0.001}, {'C': 0.01}, {'C': 0.1}, {'C': 1}, {'C': 10}],
 'split0_test_score': array([0.65104167, 0.65104167, 0.65625   , 0.734375  , 0.72395833]),
 'split1_test_score': array([0.65104167, 0.65104167, 0.65104167, 0.76041667, 0.765625  ]),
 'split2_test_score': array([0.65104167, 0.65104167, 0.65104167, 0.72916667, 0.72916667]),
 'mean_test_score': array([0.65104167, 0.65104167, 0.65277778, 0.74131944, 0.739583

In [27]:
grid_svc.best_score_, grid_svc.best_params_, grid_svc.best_estimator_

(0.7413194444444443, {'C': 1}, SVC(C=1))

In [28]:
pred = grid_dtc.best_estimator_.predict(X_test)
accuracy_score(y_test, pred)

0.75

In [29]:
grid_lr.cv_results_

{'mean_fit_time': array([0.01296504, 0.01178177, 0.01214631, 0.01164063]),
 'std_fit_time': array([7.88097108e-04, 2.54621542e-04, 6.17492163e-04, 9.31673455e-05]),
 'mean_score_time': array([0.0011034 , 0.00109235, 0.00109259, 0.00117858]),
 'std_score_time': array([1.46808164e-04, 6.70744344e-05, 4.29340310e-05, 5.04476787e-05]),
 'param_C': masked_array(data=[0.01, 0.1, 1, 10],
              mask=[False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 0.01}, {'C': 0.1}, {'C': 1}, {'C': 10}],
 'split0_test_score': array([0.75520833, 0.734375  , 0.734375  , 0.73958333]),
 'split1_test_score': array([0.796875  , 0.77083333, 0.8125    , 0.80729167]),
 'split2_test_score': array([0.74479167, 0.734375  , 0.734375  , 0.72395833]),
 'mean_test_score': array([0.765625  , 0.74652778, 0.76041667, 0.75694444]),
 'std_test_score': array([0.02250257, 0.01718662, 0.03682848, 0.03616782]),
 'rank_test_score': array([1, 4, 2, 3], dtype=int32)}

In [30]:
grid_lr.best_score_, grid_lr.best_params_, grid_lr.best_estimator_

(0.765625, {'C': 0.01}, LogisticRegression(C=0.01))

In [31]:
pred = grid_lr.best_estimator_.predict(X_test)
accuracy_score(y_test, pred)

0.8020833333333334

- 실제 값을 주고 당뇨병 여부 확인

In [48]:
test = [4, 110, 92, 0, 0, 37.6, 0.191, 30]
predict = dtc.predict(np.array(test).reshape(1, 8))
predict[0]

0