In [63]:
import numpy as np
import pandas as pd

## 1. Label encoding

In [1]:
from sklearn.preprocessing import LabelEncoder

In [12]:
items = ['TV', 'fridge', 'microwave', 'computer', 'fan', 'fan', 'mixer', 'mixer']

In [31]:
# 레이블 인코더 객체 생성
encoder = LabelEncoder()

In [32]:
# 인코딩 학습
encoder.fit(items)

LabelEncoder()

In [33]:
labels = encoder.transform(items)
labels

array([0, 3, 4, 1, 2, 2, 5, 5])

In [18]:
# Welcome to the battle
labels = encoder.fit_transform(items)
labels

array([0, 3, 4, 1, 2, 2, 5, 5])

In [52]:
# Fastest way
labels = LabelEncoder().fit_transform(items)
labels

array([0, 3, 4, 1, 2, 2, 5, 5])

## 2. One-Hot encoding

In [21]:
from sklearn.preprocessing import OneHotEncoder

In [53]:
labels = LabelEncoder().fit_transform(items)
labels = labels.reshape(-1, 1)

In [56]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
one_hot = oh_encoder.transform(labels)
one_hot.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.]])

In [51]:
# Welcome to the battle
labels = LabelEncoder().fit_transform(items)
oh_encoder = OneHotEncoder()
one_hot = oh_encoder.fit_transform(labels.reshape(-1, 1))
one_hot.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.]])

In [57]:
labels = LabelEncoder().fit_transform(items)
OneHotEncoder().fit_transform(labels.reshape(-1, 1)).toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.]])

## 3. Standard Scaler

In [59]:
from sklearn.preprocessing import StandardScaler

In [58]:
from sklearn.datasets import load_iris
iris = load_iris()

In [69]:
scaler = StandardScaler()
iris_stsc = scaler.fit_transform(iris.data)

In [66]:
df = pd.DataFrame(iris_stsc, columns = iris.feature_names)
df['species'] = iris.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0            -0.900681          1.019004          -1.340227         -1.315444   
1            -1.143017         -0.131979          -1.340227         -1.315444   
2            -1.385353          0.328414          -1.397064         -1.315444   
3            -1.506521          0.098217          -1.283389         -1.315444   
4            -1.021849          1.249201          -1.340227         -1.315444   
..                 ...               ...                ...               ...   
145           1.038005         -0.131979           0.819596          1.448832   
146           0.553333         -1.282963           0.705921          0.922303   
147           0.795669         -0.131979           0.819596          1.053935   
148           0.432165          0.788808           0.933271          1.448832   
149           0.068662         -0.131979           0.762758          0.790671   

     species  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
145        2  
146        2  
147        2  
148        2  
149        2  

[150 rows x 5 columns]

In [70]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count       1.500000e+02      1.500000e+02       1.500000e+02   
mean       -1.690315e-15     -1.842970e-15      -1.698641e-15   
std         1.003350e+00      1.003350e+00       1.003350e+00   
min        -1.870024e+00     -2.433947e+00      -1.567576e+00   
25%        -9.006812e-01     -5.923730e-01      -1.226552e+00   
50%        -5.250608e-02     -1.319795e-01       3.364776e-01   
75%         6.745011e-01      5.586108e-01       7.627583e-01   
max         2.492019e+00      3.090775e+00       1.785832e+00   

       petal width (cm)     species  
count      1.500000e+02  150.000000  
mean      -1.409243e-15    1.000000  
std        1.003350e+00    0.819232  
min       -1.447076e+00    0.000000  
25%       -1.183812e+00    0.000000  
50%        1.325097e-01    1.000000  
75%        7.906707e-01    2.000000  
max        1.712096e+00    2.000000

## 4. Min-Max scaler

In [72]:
from sklearn.preprocessing import MinMaxScaler
mm_scaler = MinMaxScaler()
iris_mms = mm_scaler.fit_transform(iris.data)

In [73]:
df2 = pd.DataFrame(iris_mms, columns = iris.feature_names)
df2

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             0.222222          0.625000           0.067797          0.041667
1             0.166667          0.416667           0.067797          0.041667
2             0.111111          0.500000           0.050847          0.041667
3             0.083333          0.458333           0.084746          0.041667
4             0.194444          0.666667           0.067797          0.041667
..                 ...               ...                ...               ...
145           0.666667          0.416667           0.711864          0.916667
146           0.555556          0.208333           0.677966          0.750000
147           0.611111          0.416667           0.711864          0.791667
148           0.527778          0.583333           0.745763          0.916667
149           0.444444          0.416667           0.694915          0.708333

[150 rows x 4 columns]

In [74]:
df2.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            0.428704          0.440556           0.467458   
std             0.230018          0.181611           0.299203   
min             0.000000          0.000000           0.000000   
25%             0.222222          0.333333           0.101695   
50%             0.416667          0.416667           0.567797   
75%             0.583333          0.541667           0.694915   
max             1.000000          1.000000           1.000000   

       petal width (cm)  
count        150.000000  
mean           0.458056  
std            0.317599  
min            0.000000  
25%            0.083333  
50%            0.500000  
75%            0.708333  
max            1.000000